<?php

function lrb_snowplow_page_attachments_alter(array &$attachments) {
  $config = \Drupal::config('lrb_snowplow.settings');
	
	$enabled = $config->get('lrb_snowplow.code.snowplow_active');

	// check if enabled
	if ($enabled == TRUE) {
		// check if not logged in
		if (\Drupal::currentUser()->isAnonymous()) {

			$attachments['#attached']['html_head'][] = [
			  [
			  	'#type'  => 'html_tag',
			    '#tag'   => 'script',
			    '#value' => $config->get('lrb_snowplow.code.snowplow_script'),
			  ], 
			  'lrb_snowplow'
			];
		}
	}
}