<?php

use \Drupal\Core\Form\FormStateInterface;

function weaver_accessibility_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	// dpm($form_id);
	// dpm($form);

	switch ($form_id) {
	}
}

function weaver_accessibility_preprocess_html(&$variables) {
  $variables['#attached']['library'][] =  'weaver_accessibility/weaver_accessibility';
}

function weaver_accessibility_theme($existing, $type, $theme, $path) {
  return [
    'weaver_text_resizer' => [
      'variables' => [],
    ],  
  ];
}