on:
  workflow_dispatch: { }
  push:
    branches: [ "main" ]
    paths: [ "app/**" ]
  create:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "tools"
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SILVER_SERVER_URL }}
        openshift_token: ${{ secrets.OPENSHIFT_SILVER_PIPELINE_TOKEN }}
        namespace: "${{ secrets.OPENSHIFT_SILVER_LICENSE_PLATE }}-tools"

    - name: Docker Login
      run: |
        docker login -u openshift -p $(oc whoami -t) "${OPENSHIFT_SILVER_EXTERNAL_REPOSITORY}/${{ secrets.OPENSHIFT_SILVER_LICENSE_PLATE }}-tools"

#    - name: Build from Dockerfile
#      id: build-image
#      uses: docker/build-push-action@v2
#      with:
#        push: true
#        tags: |
#          ${{ secrets.openshift_external_repository }}/${{ env.OPENSHIFT_NAMESPACE }}/${{ inputs.app_name }}:latest
#          ${{ secrets.openshift_external_repository }}/${{ env.OPENSHIFT_NAMESPACE }}/${{ inputs.app_name }}:${{ inputs.app_version }}
#        context: "./${{ inputs.working_directory }}"
#        file: "./${{ inputs.working_directory }}/${{ inputs.dockerfile }}"
#        build-args: |
#          APP_NAME=${{ inputs.app_name }}
#          APP_VERSION=${{ inputs.app_version }}

